name = "la-pistaccheria-r2-upload-worker"
main = "src/index.ts"
compatibility_date = "2026-06-06"

[[r2_buckets]]
bucket_name = "lapistaccheria-assets"
binding = "MEDIA_ASSETS_BUCKET"

[vars]
SUPABASE_URL = "https://lubniqdgxohcjttpozmo.supabase.co"
MEDIA_CDN_BASE_URL = "https://cdn.lapistaccheria.leandrom.com.br"